apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
 name: xbuckets.example.crossplane.io
spec:
  group: example.crossplane.io
  names:
    kind: XBuckets
    plural: xbuckets
  versions:
  - name: v1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              region: 
                type: string
              names: 
                type: array
                items:
                  type: string
